config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  # Ресурс пользователей (экшен destroy не поддерживается)
  resources :users, except: [:destroy]

  # Ресурс сессий (только три экшена :new, :create, :destroy)
  resources :sessions, only: [:new, :create, :destroy]

  # Ресурс вопросов (кроме экшенов :show, :new, :index)
  resources :questions, except: [:show, :new, :index]

  # Синонимы путей — в дополнение к созданным в ресурсах выше.
  #
  # Для любознательных: синонимы мы добавили, чтобы показать одну вещь и потом
  # их удалим.
  get 'sign_up' => 'users#new'
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  validates :text, :user,  presence: true
  validates :text, length: { maximum: 250 }
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  ITERATIONS = 20_000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions

  validates :email, :username, presence: true
  validates :username, uniqueness: { case_sensitive: false }
  validates :email, uniqueness: true

  validates :email, format: {
    with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create
  }

  validates :username, length: { maximum: 40 }
  validates :username, format: { with: /\A[A-Za-z0-9_]+\z/, on: :create }
  attr_accessor :password

  validates_presence_of :password, on: :create
  validates_confirmation_of :password

  # before_create :username_check
  before_save :encrypt_password
  before_save :username_downcase

  def username_downcase
    username.downcase!
  end

  def encrypt_password
    if self.password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(self.password,
                                   self.password_salt,
                                   ITERATIONS,
                                   DIGEST.length,
                                   DIGEST)
      )
    end
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)

    return nil unless user.present?

    hashed_password = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )

    return user if user.password_hash == hashed_password

    nil
  end
end

app/controllers/application_controller.rb
# Класс основного контроллера.
#
# От него мы будем наследовать контроллеры отдельных ресурсов.
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  #
  # Эта строчка вызывает метод, который обеспечивает защиту от поддельных форм
  # в каждой форме есть специальный уникальный токен, который rails-приложение
  # сгенерировало специально для этой формы и который нужно отправить вместе
  # с запросом, чтобы сервер его принял.
  #
  # http://guides.rubyonrails.org/security.html#cross-site-request-forgery-csrf
  protect_from_forgery with: :exception

  # Чтобы метод current_user был доступен в шаблона, нам необходимо объявить
  # его с помощью метода helper_method. Эта строка как бы говорит рельсам:
  # если в шаблоне встретишь current_user — не пугайся, что такого метода нет,
  # дерни этот метод у контроллера.
  helper_method :current_user

  private

  # Метод контроллера, достающий текущего юзера из базы по данным аутентификации
  # в сессии.
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # Метод, который редиректит посетителя на главную с предупреждением о
  # нарушении доступа. Мы будем использовать этот метод, когда надо запретить
  # пользователю что-то.
  def reject_user
    redirect_to root_path, alert: 'Вам сюда низя!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = [
      User.new(
        id: 1,
        name: 'Josh',
        username: 'solar',
        avatar_url: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=100'
      ),
      User.new(
        id: 2,
        name: 'Nick',
        username: 'bear_brown'
      )
    ]
  end

  def new
  end

  def edit
  end

  def show
    @user = User.new(
      name: 'Josh',
      username: 'solar',
      avatar_url: 'https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50?s=100'
    )

    @questions = [
      Question.new(text: 'How are you?', created_at: Date.parse('27.03.2017')),
      Question.new(text: 'How are you?', created_at: Date.parse('27.03.2017')),
      Question.new(text: 'How are you?', created_at: Date.parse('27.03.2017')),
      Question.new(text: 'How are you?', created_at: Date.parse('27.03.2017')),
      Question.new(text: 'How are you?', created_at: Date.parse('27.03.2017')),
      Question.new(text: 'How are you?', created_at: Date.parse('27.03.2017')),
      Question.new(text: 'Where are you?', created_at: Date.parse('31.10.2017'))
    ]

    @new_question = Question.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.jpg'
    end
  end

  def sklonenie(number, var1, var2, var3)
    remainder = number % 10
    return var3 if number.to_s.match?(/(11|12|13|14)$/)
    return var1 if remainder == 1
    return var2 if (remainder >= 2) && (remainder <= 4)
    return var3 if (remainder > 4) || remainder.zero?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <title>Хорошие вопросы</title>
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <div class="header-logo">
          <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
        </div>

        <%# Выводим в хэдере информацию для логина/авторизации/регистрации %>
        <div class="header-nav">
          <%# Если есть текущий юзер (значит он залогинен) %>
          <% if current_user %>
            <%# Даем ссылки на его профиль и на логаут %>
            <%= link_to "@#{current_user.username}", user_path(current_user) %> |
            <%= link_to 'Выйти', log_out_path %>
          <% else %>
            <%# Если нету — ссылки на регистрацию и логин %>
            <%= link_to 'Зарегистрироваться', sign_up_path,
            class: 'button button-light button-small' %>
          <%= link_to 'Войти', log_in_path,
            class: 'button button-light button-small' %>
        <% end %>
        </div>
      </div>
    </div>

    <div class="content">
      <div class="container">
        <%# Выводим сообщение об ошибке или уведомление для пользователя. %>
        <%# Если в объеккте flash есть что-то, выводим содержимое на страницу, %>
        <%# если нет, игнорируем этот блок. %>
        <% if flash.any? %>
          <div class="content-wrapper buffer-both">
            <% flash.each do |name, message| %>
              <%= content_tag :div, message, class: "flash-#{name}" %>
            <% end %>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= question.text  %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer if question.answer.present? %>
      </div>
    <% end %>

    <div class="question-date">
      <%= question.created_at.strftime('%d %b %M: %H') %>
    </div>

  </div>
</div>

app/views/users/edit.html.erb
<%# Страница редактирования пользователя %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for(@user) do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label 'Ваше имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      </div>
    <% end %>

    <%# Подробнее про помощники для создания форм: %>
    <%# http://guides.rubyonrails.org/form_helpers.html %>
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Our users</h1>
  </div>

  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="user-header text-center">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class='user-image-div'>
    <%= image_tag user_avatar(@user), alt: '[Picture of me]' %>
  </div>

  <h2 class='title-small buffer-both'>
    @<%= @user.username %>
  </h2>
  <div class='user-ask-button container text-center'>
    <%= link_to 'Ask me', '', class: 'button button-light', id: 'ask-button' %>
  </div>
</div>

<div class='user-question-form-div column-1-4 column-1-4-right' id='ask-form'>
  <div class='user-question-form buffer-both'>
    <div class='form'>
      <%= form_for @new_question do |f| %>
        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= f.label "Your question for @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>

        <div class="form-action">
          <%= submit_tag 'Ask a question', class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>

<div class="column-3-4">
  <div class='question-content'>
    <div class='question-text text-lead content'>
      <h1><%= "User has #{@questions.count} #{sklonenie(@questions.count, 'vopros', 'voprosa', 'voprosov')}" %></h1>
    </div>
  </div>
</div>